---
- name: AWX first YAML
  hosts: ansible
  gather_facts: FALSE

  tasks:
#  - name: query all tenants
#    aci_tenant:
#      host: '10.4.255.5'
#      username: 'admin'
#      password: 'C1sc0123'
#      state: query
#      validate_certs: no
#    delegate_to: localhost
#    register: all_tenants
  - name: Add a new leaf_interface_profile
    aci_interface_policy_leaf_profile:
      host: '10.4.255.5'
      username: admin
      password: 'C1sc0123'
      leaf_interface_profile: Leaf-501-Interface-5
      description:  description of Leaf-501-Interface-5
      state: present
      validate_certs: no
    delegate_to: localhost

  - name: Query all access port blocks under given leaf interface profile
    aci_access_port_block_to_access_port:
      host: '10.4.255.5'
      username: admin
      password: 'C1sc0123'
      leaf_interface_profile: Leaf-501-Interface-5
      state: query
      validate_certs: no
    delegate_to: localhost
    register: query_result

#  - name: Associate an access port block (single port) to an interface selector
#    aci_access_port_block_to_access_port:
#      host: '10.4.255.5'
#      username: admin
#      password: 'C1sc0123'
#      leaf_interface_profile: Leaf-501-interface-5
#      access_port_selector: AccessPort-1-5
#      leaf_port_blk: block2
#      from_port: 5
#      to_port: 5
#      state: present
#      validate_certs: no
#    delegate_to: localhost

  - name: Associate an Interface Access Port Selector to an Interface Policy Leaf Profile with a Policy Group
    aci_access_port_to_interface_policy_leaf_profile:
      host: '10.4.255.5'
      username: admin
      password: 'C1sc0123'
      leaf_interface_profile: 'Leaf-501-interface-5'
      access_port_selector: 'AccessPort-1-5'
      leaf_port_blk: 'block2'
      from_port: '5'
      to_port: '5'
      policy_group: 'leaf-access-pol-1-5'
      state: present
      validate_certs: no
    delegate_to: localhost


