---
- name: AWX first YAML
  hosts: localhost
  gather_facts: FALSE
  vars:
    api_info: &api_info
      host: '10.4.255.5'
      username: admin
      password: 'C1sc0123'
  tasks:
  - name: query all tenants
    aci_tenant:
      <<: *api_info
      state: query
      validate_certs: no
    delegate_to: localhost
    register: all_tenants
  - name: debug register
    debug:
      msg: "{{ all_tenants }}"
